### ISSUE TITLE
Iterator Not Closed in fetchMintAllowanceSupply()

### ISSUE THREAD

**Issue by Jehosephat** [GalaChain/sdk#271] opened 2024-06-18 14:09 UTC
The function fetchMintAllowanceSupply() uses an iterator to fetch state by range but does not explicitly close the iterator after its usage. Failing to close the iterator can lead to resource leaks, which can impact the performance and stability of the chaincode, especially if the function is called frequently.

Scenario
When the fetchMintAllowanceSupply function is invoked, it creates an iterator to traverse a range of states. If this function is called multiple times without properly closing the iterator, it can lead to an accumulation of unclosed iterators, eventually exhausting system resources.

Recommendation
Ensure that the iterator is properly closed after its usage by adding a finally block to close the iterator, as shown below:

try {
  for await (const kv of iterator) {
    // Loop logic...
  }
} catch (e) {
  throw new Error(`Failed to get iterator for getStateByRange with key: ${startKey}, ${iterator}, ${e}`);
} finally {
  await iterator.close();
}

Certik finding: MAS-01

**Comment by dzikowski** [comment] 2024-06-21 11:30
this is not an issue, iterator is closed automatically by design

duplicate of: https://github.com/GalaChain/sdk/issues/154

**Closed by dzikowski** 2024-06-21 11:30 UTC
