### ISSUE TITLE
Cannot change channel name

### ISSUE THREAD

**Issue by herr-bubu** [GalaChain/sdk#233] opened 2024-05-17 06:40 UTC
When using SDK and working on chaincode that has a different name than `product-channel` I get an error during e2e tests. It always looks for `product-channel` so with different name it can't be discovered.

**Comment by befitsandpiper** [comment] 2024-06-12 00:16
I think the issue is in each chaincode's channel configuration in ops-api-config.json file, and also potentially the .gitlab-ci.yml files for configuration. I do not believe this is an issue with sdk though. If this seems correct, we can close this ticket.

**Closed** 2024-06-27 05:58 UTC
